name: Daily Watch Scrape

on:
  # 1. Lancement manuel (permet de tester ou de lancer dès le premier push)
  workflow_dispatch:

  # 2. Planification quotidienne à 11h UTC (~12h-13h en France)
  schedule:
    - cron: '0 11 * * *'  # Tous les jours à 11h00 UTC

permissions:
  contents: write

jobs:
  scrape-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python scraper.py

      - name: Commit and push if index.html changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add index.html
          timestamp=$(date -u)
          git commit -m "Daily update: ${timestamp}" || echo "No changes to commit"
          git push